name: medihub_tests
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.6+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.3.2
  provider: ^6.0.0
  animated_check: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  flutter_google_places_sdk: ^0.4.2+1
  google_places_flutter: ^2.0.8
  lottie: ^3.1.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/medihub-icon-android.png"
  adaptive_icon_background: null
  adaptive_icon_foreground: null

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  


  assets:
    - assets/images/
    - assets/images/wheelchairs/
    - assets/images/mobilityscooters/
    - assets/images/dailyaids/
    - assets/images/homecare/
    - assets/icons/
    - .env
    - assets/animations/

    