// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVD57h8w5q77fyGwHUUiDsZ7MXJtqOwcA',
    appId: '1:325769946334:web:f77c2cb3fc16354e924e4f',
    messagingSenderId: '325769946334',
    projectId: 'mills-brands-websites',
    authDomain: 'mills-brands-websites.firebaseapp.com',
    storageBucket: 'mills-brands-websites.appspot.com',
    measurementId: 'G-P580DC3GSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvORr2jLVPFTnCd4ifcD1Jr1Qcxheu_F8',
    appId: '1:325769946334:android:ca3bbe327399de7b924e4f',
    messagingSenderId: '325769946334',
    projectId: 'mills-brands-websites',
    storageBucket: 'mills-brands-websites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuwIvEGHulCb7lEmhPEBi82qOS7qqZILM',
    appId: '1:325769946334:ios:fe5e695f79e26fd2924e4f',
    messagingSenderId: '325769946334',
    projectId: 'mills-brands-websites',
    storageBucket: 'mills-brands-websites.appspot.com',
    iosBundleId: 'com.example.medihubTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuwIvEGHulCb7lEmhPEBi82qOS7qqZILM',
    appId: '1:325769946334:ios:fe5e695f79e26fd2924e4f',
    messagingSenderId: '325769946334',
    projectId: 'mills-brands-websites',
    storageBucket: 'mills-brands-websites.appspot.com',
    iosBundleId: 'com.example.medihubTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRDvHLGbtpC17jZsA_lxvEFR88HECafr0',
    appId: '1:325769946334:web:7c3feffb6119406e924e4f',
    messagingSenderId: '325769946334',
    projectId: 'mills-brands-websites',
    authDomain: 'mills-brands-websites.firebaseapp.com',
    storageBucket: 'mills-brands-websites.appspot.com',
    measurementId: 'G-MZJC1BYZE5',
  );
}
